sudo: required
services:
    - docker
language: rust
env:
  global:
  - BGPTOOLS_VERSION=0.0.2
before_script:
  - sudo apt update && sudo apt install lftp
  - cargo install --vers $BGPTOOLS_VERSION bgptools
  - export PATH=$PATH:/home/travis/.cargo/bin
  - docker pull yangzhaofengsteven/cidr-merge
  - docker pull gaoyifan/bgpdump
script:
  - ./generate.sh
  - ./stat.sh
deploy:
  provider: script
  script: ./upload.sh
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_EVENT_TYPE == cron
