name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

  workflow_dispatch:
  schedule:
    - cron: '45 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cargo-bins/cargo-binstall@main
      - uses: extractions/setup-just@v3
      - uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-cargo-bin-${{ hashFiles('justfile') }}
          restore-keys: ${{ runner.os }}-cargo-bin-
          path: ~/.cargo/bin
      - run: just dependency
      - uses: nick-fields/retry@v3
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: just
      - run: just guard
      - name: Checkout ip-lists branch
        uses: actions/checkout@v6
        if: github.event_name == 'schedule' && github.ref == 'refs/heads/master'
        with:
          ref: ip-lists
          path: ip-lists
      - run: just upload
        if: github.event_name == 'schedule' && github.ref == 'refs/heads/master'
      - run: just refresh_jsdelivr ${{ github.repository }}
        if: github.event_name == 'schedule' && github.ref == 'refs/heads/master'

